//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.Imagenes1 = new HashSet<Imagenes>();
        }
    
        public int IdArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioVenta { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdCate { get; set; }
        public Nullable<int> IdImagen { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public string Existencia { get; set; }
        public byte[] Imagen { get; set; }

        public virtual Categoria Categoria { get; set; }
        public virtual Imagenes Imagenes { get; set; }
        public virtual Material Material { get; set; }
        public virtual TipoArt TipoArt { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Tallas Tallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagenes> Imagenes1 { get; set; }
    }
}
